spring:
  profiles:
    active: local

---

spring:
  jpa:
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: validate
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 20MB
  jackson:
    property-naming-strategy: SNAKE_CASE

---

auth.jwt:
  issuer: ${jwt-issuer}
  jwtSecret: ${jwt-secret-key}
  jwtExpiration: 7200
  refreshExpiration: 172800

cloud:
  aws:
    credentials:
      instance-profile: true
    region:
      static: ap-northeast-2
    stack:
      auto: false
    s3:
      bucket: ggzz-bucket-dev

---

server:
  servlet:
    session:
      cookie:
        same-site: none
        secure: true

---

spring:
  config:
    activate:
      on-profile: dev

secrets-manager: dev/ggzz-server

---

spring:
  config:
    activate:
      on-profile: local
  jpa:
    open-in-view: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/infp_db
    username: infp
    password: INFP_admin_01
