spring:
  profiles:
    active: local

---

spring:
  jpa:
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 20MB

cloud:
  aws:
    credentials:
      instance-profile: true
    region:
      static: ap-northeast-2
    stack:
      auto: false
    s3:
      bucket: ggzz-bucket-dev

ggzz:
  jwt:
    issuer: ggzz-server
    secret: WAFFLE_STUDIO_GGZZ_JSON_WEB_TOKEN_SECRET_KEY
    expiration: 7200

---

spring:
  config:
    activate:
      on-profile: dev

secrets-manager: dev/ggzz-server

---

spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:mysql://localhost:3306/infp_db
    username: infp
    password: INFP_admin_01

logging:
  level:
    org.springframework.security: TRACE
