spring:
  profiles:
    active: dev

---

spring:
  jpa:
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 20MB
  jackson:
    property-naming-strategy: SNAKE_CASE

---

cloud:
  aws:
    credentials:
      instance-profile: true
    region:
      static: ap-northeast-2
    stack:
      auto: false
    s3:
      bucket: ggzz-bucket-dev

---

server:
  servlet:
    session:
      cookie:
        same-site: none
        secure: true

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ${dev.datasource.url}
    username: ${dev.datasource.username}
    password: ${dev.datasource.password}

secrets-manager: dev/ggzz-server

---

spring:
  config:
    activate:
      on-profile: local
  jpa:
    open-in-view: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/infp_db
    username: infp
    password: INFP_admin_01

secrets-manager: dev/ggzz-server
